import { Geist, Geist_Mono, JetBrains_Mono } from "next/font/google";
import "./globals.css";

// components
import Header from "@/components/Header";
import PageTransition from "@/components/ui/PageTransition";
import StairsTransition from "@/components/ui/StairsTransition";
import Footer from "@/components/Footer";
import SideProfile from "@/components/SideProfile";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const jetbrainsMono = JetBrains_Mono({
  variable: "--font-jetbrainsMono",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"]
});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} ${jetbrainsMono.variable} antialiased`}>
        <Header />
        {/*<StairsTransition/>}
        <PageTransition>{children}</PageTransition>
        {*/}

        <section className=" h-full px-1 py-3 xl:py-1overflow-hidden">
          <div className="mx-auto h-full container overflow-y-auto">
            <div className="flex flex-col xl:flex-row items-start xl:items-top gap-5">
              {/* Left Side: SideProfile */}
                <aside className="w-full lg:w-[20%] bg-primary overflow-auto">
                  <SideProfile />
                </aside>
            {/* Right Side: Page Content */}
                <section className="w-full lg:w-[80%] bg-primary overflow-auto">
                  {children}
                  <Footer />
                </section>
            </div>
          </div>
        </section>

       

      </body>
    </html>
  );
}
